services:
  papermc:
    image: yanpgabriel/minecloud
    build:
        context: ./
        dockerfile: Dockerfile
        args:
            UID: 1000
            GID: 1000
    restart: no
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: latest
      BUILD: latest
    volumes:
      - ./minecraft:/minecraft
