version: "3.8"

services:
  papermc:
    image: yanpgabriel/minecloud
    build:
        context: ./
        dockerfile: Dockerfile
    restart: no
    tty: true
    stdin_open: true
    user: "1000:1000"
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: latest
      BUILD: latest
    volumes:
      - ./minecraft:/minecraft